<?php

/**
 * @file
 * Hooks for Hux Test.
 */

use Drupal\hux_test\HuxTestCallTracker;

/**
 * Implements hook_foo().
 */
function hux_test_foo(): string {
  HuxTestCallTracker::record(__FUNCTION__);
  return __FUNCTION__ . ' return';
}

/**
 * Implements hook_foo2().
 */
function hux_test_foo2(): string {
  HuxTestCallTracker::record(__FUNCTION__);
  return __FUNCTION__ . ' return';
}

/**
 * Implements hook_foo3().
 */
function hux_test_foo3(): string {
  HuxTestCallTracker::record(__FUNCTION__);
  return __FUNCTION__ . ' return';
}

/**
 * Implements hook_foo4().
 */
function hux_test_foo4(): string {
  HuxTestCallTracker::record(__FUNCTION__);
  return __FUNCTION__ . ' return';
}

/**
 * Implements hook_original_invoker_attribute_first().
 */
function hux_test_original_invoker_attribute_first(): string {
  HuxTestCallTracker::record(__FUNCTION__);
  return __FUNCTION__ . ' return';
}

/**
 * Implements original_invoker_attribute_middle().
 */
function hux_test_original_invoker_attribute_middle(): string {
  HuxTestCallTracker::record(__FUNCTION__);
  return __FUNCTION__ . ' return';
}

/**
 * Implements original_invoker_attribute_last().
 */
function hux_test_original_invoker_attribute_last(): string {
  HuxTestCallTracker::record(__FUNCTION__);
  return __FUNCTION__ . ' return';
}
